name: OBS Upload

on:
  - push

jobs:
  obs-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run OBS Upload Script
        run: .github/workflows/obs-upload.sh
